version: 2

defaults:
  workspace_root: &workspace_root
    ~/nextjs

  nodejs_container: &nodejs_container
    working_directory: *workspace_root
    docker:
      - image: circleci/node:8-browsers

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-nextjs-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
        - v1-nextjs-dependencies-master-{{ checksum "package.json" }}
        - v1-nextjs-dependencies-master-

jobs:
  checkout:
    <<: *nodejs_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - v1-nextjs-yarn-{{ checksum "package.json" }}
            - v1-nextjs-yarn-

      - run:
          name: Install dependencies
          command: yarn --no-lockfile

      - save_cache:
          name: Save yarn cache
          key: v1-nextjs-yarn-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          name: Save node_modules cache
          key: v1-nextjs-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules/

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist/
            - test/node_modules/

  quality:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Run linter
          command: yarn lint

      - run:
          name: Run flow check
          command: yarn flow

  test-integration:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Run tests
          command: yarn testall test/integration

      - store_test_results:
          path: reports/tests/

  test-isolated:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Run tests
          command: yarn testall test/isolated

      - store_test_results:
          path: reports/tests/

  test-unit:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Run tests
          command: yarn testall test/unit

      - store_test_results:
          path: reports/tests/


workflows:
  version: 2

  push:
    jobs:
      - checkout

      - install:
          requires:
            - checkout

      - quality:
          requires:
            - install

      - test-integration:
          requires:
            - install
      - test-isolated:
          requires:
            - install
      - test-unit:
          requires:
            - install
